name: Azura
version: 1.0.0
main: me.avenzu.azura.Azura
authors: [avenzu, SkidRevenant]
description: Yet another free open-sourced anti-cheat!

commands:
  staffmode:
    description: Opens the staff mode inventory.
    usage: /<command>
    permission: azura.staffmode
    permission-message: You do not have permission to use this command.
  vanish:
    description: Vanish yourself to hide while spectating.
    usage: /vanish
    permission: azura.vanish
    permission-message: You do not have permission to vanish players.
  azura autoban:
    description: Turns azura autoban on or off.
    usage: /azura autoban true|false
    permission: azura.settings.autoban
    permission-message: You do not have permission to access Azura settings.
  mute:
    description: Mute or unmute a player.
    usage: /mute <player> <duration>
    permission: azura.mute
    permission-message: You do not have permission to mute players.
  unmute:
    description: Unmutes a player
    usage: /unmute <player>
    permission: azura.unmute
    permission-message: You do not have permission to unmute players.
  azura:
    description: Main command for Azura settings.
    permission: azura.settings
    permission-message: You do not have permission to access Azura settings.
  ban:
    description: Bans a player from the server.
    usage: /ban <player> <reason>
    permission: azura.ban
    permission-message: You do not have permission to ban players.
  unban:
    description: Unbans a player from the server.
    usage: /unban <player>
    permission: azura.unban
    permission-message: You do not have permission to unban players.
  report:
    description: Allows players to report other players.
    usage: /report <player>
    permission: azura.report
    permission-message: You do not have permission to report players.

permissions:
  azura.staffmode:
    default: op
  azura.vanish:
    default: op
  azura.mute:
    default: op
  azura.unmute:
    default: op
  azura.settings.autoban:
    default: op
  azura.settings:
    default: true
  azura.ban:
    default: op
  azura.unban:
    default: op
  azura.report:
    default: true